site_name: docs. /mijn KLOUWD
site_url: https://mijnklouwd.nl
theme:
  name: material
  logo: assets/images/12logo-mkd-25.png
  favicon: assets/images/12favi-mkd-25.png
  features:
    - navigation.footer
    - content.code.copy
  icon: 
    previous: material/arrow-left
    next: material/arrow-right
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: purple
      accent: deep orange

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: purple
      accent: deep orange


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format        
  - pymdownx.tabbed:
     alternate_style: true  
     
  - admonition
  - pymdownx.details   

extra:
  social:
    - icon: simple/youtube
      link: https://youtube.com/@klouwd
  footer_links:
    - text: Privacy  
      href: "https://mijnklouwd.nl/privacy-policy/"  
   

copyright: . &copy; / &#9829;   
